### ISSUE TITLE
B4 - Add syntax highlighting to code snippets

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/copilot-camp#199]
Let's add syntax highlighting to the code snippets to make them more readable

**Comment by rabwill** [comment]
syntax highlighting is used in most case only case where it was not used is in one section to show new modules imported using the existing package

**Comment by silverqx** [comment]
I lack this feature in the web-based interface, too. Copilot Windows desktop has a lot of other bugs and problems. The web-based interface doesn't support ```, but it's overall smoother. I would prefer it as a PWA for now.
