### ISSUE TITLE
B4 - Inconsistent auth setup

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoft/copilot-camp#200]
When configuring the TeamsAdapter, we set it to a multitenant app:

```js
const adapter = new TeamsAdapter(
  {},
  new ConfigurationServiceClientCredentialFactory({
    MicrosoftAppId: config.botId,
    MicrosoftAppPassword: config.botPassword,
    MicrosoftAppType: 'MultiTenant',
  })
);
```

But when creating the Entra app reg, we configured it as single tenant `"signInAudience": "AzureADMyOrg",`. Shouldn't these two be the same?

**Comment by rabwill** [comment]
I anyway wanted to update to multi, so have updated code and instructions, Also added a bonus tip to change to Single Tenant if needed. So devs have both options.
