### ISSUE TITLE
[Lab E6 Exercise 1] Persistent Developer tunnel URL setup

### ISSUE THREAD

**Issue by freistli** [microsoft/copilot-camp#254]
All steps are good, however when we debug the project locally, the default debug steps will always use "Start Teams App Locally" step which creates non-persist tunnel URL can cause the running failure.

My workaround is to comment this "Start local tunnel" step in task.json:

{
            "label": "Start Teams App Locally",
            "dependsOn": [
                "Validate prerequisites",
                //"Start local tunnel",
                "Create resources",
                "Build project",
                "Start application"
            ],
            "dependsOrder": "sequence"
        }

And set OPENAPI_SERVER_URL in .env.local.user as the persistent tunnel URL.

After this, local debugging works well with the persistent Tunnel url.

**Comment by BobGerman** [comment]
OK this is fixed thanks!
I'm planning to add TTK integration by the way so it will work with the dynamic tunnel.
Here is a sample using this approach FYI
https://github.com/pnp/copilot-pro-dev-samples/tree/main/samples/da-repairs-oauth-validated
