### ISSUE TITLE
[Lab E2 Exercise 3 Step 2 & Lab 6 Exercise 7 Step 3] Storage Emulator Explanation

### ISSUE THREAD

**Issue by freistli** [microsoft/copilot-camp#255]
Storage Explorer doesn't ship with an emulator. Developer needs to download one. Azurite is recommended. We can refer to: https://learn.microsoft.com/en-us/azure/storage/common/storage-explorer-emulators

Basically to use Emulator with Storage Explorer, we can:

1. Install Storage Explorer
2. Install Azurite
3. Run Azurite
4. View emulator storage in Storage Explorer

Another thing is ensure no service conflicts with the ports using by Storage Emulator (Azurite). Can use "netstat -ano > 1.txt" to quickly confirm if any ports cannot be listened.

**Comment by andrehe001** [comment]
we could add the link to Azurite as the above link does not have a link. https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio-code%2Cblob-storage

**Comment by BobGerman** [comment]
Azureite is installed as an npm package, and is handled when the user does an `npm install`.
I will add a note about this but an explicit Azurite install is not required...

**Comment by BobGerman** [comment]
Fixed in https://github.com/microsoft/copilot-camp/pull/329
Thanks for reporting!
