### ISSUE TITLE
Lab E0 Feedback - Links

### ISSUE THREAD

**Issue by pkbullock** [microsoft/copilot-camp#338]
## Lab E0

It talks about an administrator, should you be more specific e.g. Teams Administrator as that’s the defined M365 role. Also, can this align with the instructions in Lab B0, I believe they are better.

**Step 1:** 
Install VS Code dead link for the extension, 

![Screenshot 2024-10-02 214242](https://github.com/user-attachments/assets/a005ac2c-e94d-4f4c-a36c-09386f887c36)

**Step 2:**
Node.js - would you want the pre-built installer rather than the package manager?

https://nodejs.org/en/download/prebuilt-installer - the site defaults to the other one, which appears to be confusing. 

![Screenshot 2024-10-02 214657](https://github.com/user-attachments/assets/2327acde-a509-4036-80b2-bcaae23d678b)

**Comment by rabwill** [comment]
Thanks @pkbullock so much for your feedback. DA came in a lot late and hence all the confusion around releases, fixing soon :)
