### ISSUE TITLE
Lab E1 Feedback

### ISSUE THREAD

**Issue by pkbullock** [microsoft/copilot-camp#339]
## Lab E1
“Install Teams Toolkit for VS Code from this Link” takes me to a CI/CD pipline with release at the bottom – is this intended? If so, you might need some guidance on how to install a pre-pre-release version.

![Screenshot 2024-10-02 213941](https://github.com/user-attachments/assets/5364dfcc-b5f7-4082-af90-be40a9bfbb86)

**Exercise 1:** 
Scaffold a declarative agent from template
The hotfix version is that pre-release or the other CI/CD one I bumped into? This section is not clear on what is required here, maybe the word hotfix isn’t the best word.

![Screenshot 2024-10-02 214242](https://github.com/user-attachments/assets/77e15b6d-96a7-4954-ba8e-3df5b6375c8f)

The instructions when a Declarative Copilot was created shows that Node v20 isnt on the supported list, please confirm which version is required?

![Screenshot 2024-10-02 214242](https://github.com/user-attachments/assets/a08bb8d2-cea9-4890-a010-c6f7bd689067)

Stopping at this point as tenant is out of date. We resume testing lab when tenant has the updates.

**Comment by rabwill** [comment]
Thanks @pkbullock good catch while this lab was written there was a different pathway to be able to test using a hotfix version but should be okay now, we will update the steps. Appreciate your feedback :)
