### ISSUE TITLE
Feature Request: Copy button for the Code

### ISSUE THREAD

**Issue by pkbullock** [microsoft/copilot-camp#345]
I would love the ability to copy to clipboard button. 

In PnP Script Samples, I use https://clipboardjs.com/ if that helps.
It may make it easier to extract the sample code from the boxes.

![image](https://github.com/user-attachments/assets/5aae4837-c696-46af-8c12-a4db522bdffe)

**Comment by chenxizhang** [comment]
vote for this

**Comment by rabwill** [comment]
I vote too, I will try something without having to redo our file with existing code block and let us know how it looks . Can reverse it if the experience is horrible ;) @pkbullock and @chenxizhang

**Comment by rabwill** [comment]
I will keep this open and let you folks test and let me know. 
![2024-10-09_14-17-06 (1)](https://github.com/user-attachments/assets/6ab241fc-deb5-44d9-a0bd-aa80d8712b1b)

**Comment by pkbullock** [comment]
So the location would it be better to have the button top/below the box to avoid using up real estate on horizontal. Just thinking for screen width limited devices, eg tablets, mobiles.

**Comment by BobGerman** [comment]
Awesome feature I love this! It has already saved me time, thanks!

**Comment by rabwill** [comment]
> So the location would it be better to have the button top/below the box to avoid using up real estate on horizontal. Just thinking for screen width limited devices, eg tablets, mobiles.
> 
> Looks good and will be a time saver.

Yes will enhance this one Paul. Appreciate it. Will close for now.
