### ISSUE TITLE
Lab E1 Small content suggestions/issues

### ISSUE THREAD

**Issue by pkbullock** [microsoft/copilot-camp#353]
Do the preview warnings still apply now? Exercise 2 Step 3

![image](https://github.com/user-attachments/assets/2d7c7601-e9cb-4e42-8fe3-f090daf3c71c)

Exercise 3 Step 2
Question, do you think some URL examples or what is supported should be described here, can I just paste in a site, library, file.

![image](https://github.com/user-attachments/assets/66f010dd-27db-4e66-8e07-c9023ffc42d1)

Placeholder in text Exercise 3 step 4

![image](https://github.com/user-attachments/assets/4d847a7a-efd5-4a8f-9017-2e9414f6ef42)

**Comment by rabwill** [comment]
Good catch will remove this! Thanks so much :)
