### ISSUE TITLE
Lab E3 Step 1 has a reference to trey-declarative-copilot.json, Step 3 mentions trey-declarative-agent.json

### ISSUE THREAD

**Issue by cristianoag** [microsoft/copilot-camp#355]
In Lab E3, Step 1 references the file trey-declarative-copilot.json, but in Step 3, it incorrectly refers to trey-declarative-agent.json. Since the lab files use trey-declarative-copilot.json, either the documentation needs to be updated to consistently reference this file, or the file names in the lab materials should be corrected to match the documentation.

**Comment by BobGerman** [comment]
Fixed along with many many others, thanks @cristianoag 
 https://github.com/microsoft/copilot-camp/pull/366
