### ISSUE TITLE
Lab E3 Content and Feedback

### ISSUE THREAD

**Issue by pkbullock** [microsoft/copilot-camp#357]
## Missing Introduction section
Just thinking that the others have this section. What I feel is missing, is which copy of the app I am working on, I can see in the repo there is a folder and code for this, but the instructions do not reference this.

![image](https://github.com/user-attachments/assets/4adb1eeb-8854-494c-aaad-918106aab61b)

Just seen this, can this be in the instructions instead of a readme file?
![image](https://github.com/user-attachments/assets/3d6789eb-7dec-4064-a5db-74d56b879215)

## Exercise 1 - Step 2 - Sample Documents
Should "working folder" contain a reminder in the introduction or lab start just so they know what this means.
Also, its "sampleDocs" 

![image](https://github.com/user-attachments/assets/7cdf7728-aaae-43d3-815d-a6fa652bee45)

## Exercise 2 - Step 1

You have moved away from inline code fragments to pointers to content in the repo (link to solution), what this intended?
![image](https://github.com/user-attachments/assets/fd7f3ad5-6300-422a-9e32-ca274ad0b625)

## Exercise 2 - Step 4 - Missing Step Completion Tick Box

![image](https://github.com/user-attachments/assets/b0728802-d21e-492b-a4e0-2570a34f7e79)

## Exercise 3 - Step 2
Is the comment in the screenshot intended, seems accidental?
![image](https://github.com/user-attachments/assets/25e9c42a-ed0c-410e-ab0f-53456a4af33f)

**Comment by BobGerman** [comment]
THANKS very much!!
Fixed in https://github.com/microsoft/copilot-camp/pull/372
