### ISSUE TITLE
Lab B1 - First custom engine agent

### ISSUE THREAD

**Issue by alexander-kastil** [microsoft/copilot-camp#380]
https://github.com/microsoft/copilot-camp/blob/main/docs/pages/custom-engine/01-custom-engine-agent.md

Update Exercise 1 Step 2 to reflect current state of Azure AI Studio. System Prompt templates are only available in the old look which is not the default. Instead of selecting a system message template, let users enter the following system prompt:

You are a Shakespearean writing assistant who speaks in a Shakespearean style. You help people come up with creative ideas and content like stories, poems, and songs that use Shakespearean style of writing style, including words like "thou" and "hath”.
Here are some example of Shakespeare's style:
 - Romeo, Romeo! Wherefore art thou Romeo?
 - Love looks not with the eyes, but with the mind; and therefore is winged Cupid painted blind.
 - Shall I compare thee to a summer’s day? Thou art more lovely and more temperate.

**Comment by aycabas** [comment]
Labs are adjusted with the new AI Foundry.
