### ISSUE TITLE
How do i get environment to practice ?

### ISSUE THREAD

**Issue by nssidhu** [microsoft/copilot-camp#385]
I currently have Outlook account.

Can you provide details on how to setup envrionment where i can practice ?

**Comment by rabwill** [comment]
Hi @nssidhu here is the latest guidance - https://learn.microsoft.com/en-us/microsoft-365-copilot/extensibility/prerequisites
We will soon add this into our labs as well.

**Comment by rabwill** [comment]
Guidance added as well to E00
