### ISSUE TITLE
Resource: set up dev environment

### ISSUE THREAD

**Issue by jthake** [microsoft/copilot-camp#409]
In the declarative agent labs on the setup section https://microsoft.github.io/copilot-camp/pages/extend-m365-copilot/00-prerequisites/ . The page currently assumes you have a tenant to setup. 

You can reference off to the https://learn.microsoft.com/en-us/microsoft-365-copilot/extensibility/prerequisites page that explains the current way you can get a tenant.

**Comment by rabwill** [comment]
Thanks @jthake
