### ISSUE TITLE
E1 missing sharpoint integration

### ISSUE THREAD

**Issue by vacuumboots** [microsoft/copilot-camp#411]
Lab E1, section "Exercise 3: Add files for reference (Bonus exercise)" 

there are instructions to upload the two pdf files onto sharepoint, but then the reference is only the sharepoint site in general. 

"Copy the absolute url of the site. For eg. https://xyz.sharepoint.com/sites/contoso and proceed to next step." 

How are you supposed to actually utilize historical_map.pdf and travelers_diary? 

In the screenshot  "Step 4: Test the app", the  challenge is clearly not based on the travel diary. 

====
In Step 3: Upgrade app manifest
Next, go to the file appPackage/manifest.json and upgrade the manifest version from "1.0.0"" to "1.0.1" so the changes are reflected when you install.

You actually should not modify the manifest version, which needs to stay at 1.19. Instead, the version variable needs to be chaged.

**Comment by rabwill** [comment]
Hi @vacuumboots good catch on the screenshot, we will update with the right one.
You can utilise the travel diary with the conversation starters we have added for both historical_map.pdf and travelers_diary?
You are also right about the usage of manifest "version" and from saying "1.0.0"" to "1.0.1" we thought it was implied to be version of the overall app and not manifest. We will remove the incorrect labelling. Thank again.
