### ISSUE TITLE
About the action planner's prompt

### ISSUE THREAD

**Issue by gillesev** [microsoft/copilot-camp#426]
The choosePrompt function (in https://github.com/microsoft/copilot-camp/blob/main/src/custom-engine-agent/Lab05-Actions/CareerGenie/src/app/app.ts) does feel like the AI is co-opted again by an if/else statement. Why can't the central AI decide which prompt to use based on input?

**Comment by rabwill** [comment]
@aycabas

**Comment by aycabas** [comment]
Unfortunately, this is a limitation of Teams AI library when it comes to multi prompt implementations. Until further changes in the AI library that allows us to centralize planner to choose between prompts, we'll have to carry on with our basic if/else logic.
