### ISSUE TITLE
Lab B2: Error 400 Validation error at #/data_sources/0/azure_search/parameters/indexName: Extra inputs are not permitted

### ISSUE THREAD

**Issue by mohammadamer** [microsoft/copilot-camp#429]
I got an issue when I reached Lab2 of "Build your own agent"

Error 400 Validation error at #/data_sources/0/azure_search/parameters/indexName: Extra inputs are not permitted

`CHAT PROMPT:
[
  {
    "role": "system",
    "content": "You are a career specialist named \"Career Genie\" that helps Human Resources team for finding the right candidate for the jobs. \r\nYou are friendly and professional.\r\nYou always greet users with excitement and introduce yourself first.\r\nYou like using emojis where appropriate.\r\nAlways mention all citations in your content."
  },
  {
    "role": "user",
    "content": "hi"
  }
]
BadRequestError: 400 Validation error at #/data_sources/0/azure_search/parameters/indexName: Extra inputs are not permitted
    at Function.generate (C:\github\CareerGenie\node_modules\openai\src\error.ts:70:14)
    at AzureOpenAI.makeStatusError (C:\github\CareerGenie\node_modules\openai\src\core.ts:435:21)
    at AzureOpenAI.makeRequest (C:\github\CareerGenie\node_modules\openai\src\core.ts:499:24)
2:16) {
  status: 400,
  headers: {
    'apim-request-id': '9e91dfc8-987c-4de9-8fa3-3b424fd57403',
    'content-length': '194',
    'content-type': 'application/json; charset=UTF-8',
    date: 'Fri, 13 Dec 2024 09:08:39 GMT',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'x-content-type-options': 'nosniff',
    'x-envoy-upstream-service-time': '11',
    'x-ms-region': 'Norway East',
    'x-ratelimit-remaining-requests': '79',
    'x-ratelimit-remaining-tokens': '6918'
  },
  request_id: undefined,
  error: {
    requestid: '9e91dfc8-987c-4de9-8fa3-3b424fd57403',
    code: 400,
    message: 'Validation error at #/data_sources/0/azure_search/parameters/indexName: Extra inputs are not permitted'
  },
  code: 400,
  param: undefined,
  type: undefined
}
ERROR:
400 Validation error at #/data_sources/0/azure_search/parameters/indexName: Extra inputs are not permitted       
HEADERS:
{
  "apim-request-id": "9e91dfc8-987c-4de9-8fa3-3b424fd57403",
  "content-length": "194",
  "content-type": "application/json; charset=UTF-8",
  "date": "Fri, 13 Dec 2024 09:08:39 GMT",
  "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
  "x-content-type-options": "nosniff",
  "x-envoy-upstream-service-time": "11",
  "x-ms-region": "Norway East",
  "x-ratelimit-remaining-requests": "79",
  "x-ratelimit-remaining-tokens": "6918"
}`

**Comment by aycabas** [comment]
Hi @mohammadamer, please double check your index name and make sure it's same with your index created on Azure AI Search. You are getting a validation error that means the index name you've mentioned in your env files doesn't exist in Azure AI Search. Let me know if you still have the same issue.

**Comment by mohammadamer** [comment]
Hi @aycabas 
It's the same name of the index that I have created in the Azure AI search.

INDEX_NAME='resumes'

![Image](https://github.com/user-attachments/assets/f4e7255d-e9de-4e90-8ce7-df9b213a3459)

**Comment by aycabas** [comment]
Perfect, then it was a parameter issue. I'm glad you've fixed it 😊
