### ISSUE TITLE
Lab B5: sendEmail.ok, status or statusText properties do not exist

### ISSUE THREAD

**Issue by jmservera** [microsoft/copilot-camp#434]
These properties are not returned by the Graph API:

https://github.com/microsoft/copilot-camp/blob/7b7934de873cd0b3968c6ca24258aa8dfe9e0187/docs/pages/custom-engine/05-actions.md?plain=1#L482-L488

An exception should be catched instead.

**Comment by aycabas** [comment]
Hi @jmservera, @rabwill thank you for pointing this out, let me have a look at the try/catch options before removing the existing status check entirely, I believe current status check plays an important role for debugging. I'd rather advance this part than simplify it. I'll definitely have a look at better options for catching errors here. Thanks.
